version: '3.8'

volumes:
  pg_data:

networks:
  postgres:

secrets:
  pg_password:
    file: secret.pg_password.txt

services:
  postgres:
    image: docker.io/library/postgres:17.2
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_INITDB_ARGS=${POSTGRES_INITDB_ARGS---data-checksums}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD-}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg_password
      - POSTGRES_DB=${POSTGRES_DB:-$POSTGRES_USER}
      - TZ=${TZ:-UTC}
    secrets:
      - pg_password
    ports:
      - 5432:5432
    networks:
      - postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U "${POSTGRES_USER:-postgres}"']
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 5
