version: '3.8'

volumes:
  pg_data:

networks:
  keycloak:

services:

  postgres:
    image: postgres:14.4
    container_name: postgres
    restart: on-failure:2
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_MULTIPLE_DATABASES=keycloak
    ports:
      - 5432:5432
    networks:
      - keycloak
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 30s
      timeout: 20s
      retries: 3

  keycloak:
    image: jboss/keycloak:16.1.1
    container_name: keycloak
    restart: on-failure:2
    depends_on:
      - postgres
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
    ports:
      - 8080:8080
    networks:
      - keycloak
